### ISSUE TITLE
broken on kterm (kindle terminal)

### ISSUE THREAD

**Issue by mackdroid** [ayn2op/discordo#319]
![image](https://github.com/ayn2op/discordo/assets/68280146/2b110084-b9e9-4475-a7c3-e1e97e38a09b)

**Comment by ghost** [comment]
Kterm is kind of a dead project. Last updated 2 years ago.
 
And @ayn2op, should we make a config to turn off all colors (aka a monochrome switch)?

**Comment by ayn2op** [comment]
> Kterm is kind of a dead project. Last updated 2 years ago.
> 
> And @ayn2op, should we make a config to turn off all colors (aka a monochrome switch)?

Set the `TERM` variable to `xterm` to run it in monochrome mode (eg: `TERM=xterm discordo`)
