### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by hafizdkren** [ayn2op/discordo#86]
So the Discordo is had some issue when try to open. since it can be from discord itself where forcing to using hCaptcha to prevent spam bot exist. this is making to login via terminal is difficult for people who are trying to using Discordo.

For more info, I'll try to Screenshot later.

**Comment by ghost** [comment]
Discord uses [hCaptcha](https://www.hcaptcha.com/) ― unfortunately, `hCaptcha` provides no such API to solve the captcha externally (i.e. using an HTTP request). However, there is a workaround, you can log in using the account email and password from the browser (if you are already logged into your account, you can skip this step), retrieve the client authentication token from developer tools, and assign the `token` command-line flag in the retrieved token.

**Comment by hafizdkren** [comment]
So base on you suggestion is to copying my token into somewhere like .zshenv or something with name that 'discordo' understand it like what been explain on "README.md", right?

**Comment by hafizdkren** [comment]
All right then, thanks for workaround. I'll try to putting better "README.md" so people who interest with the project can understand more better on the program
